config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#top'
  devise_for :users
  resources :books ,only: [:index, :create, :show, :edit ,:update, :destroy]
  resources :users ,only: [:index, :show, :edit, :update]
  get 'home/about' => 'home#about'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
  	user_path(current_user.id)
  end

  

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]
	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		    flash[:notice_a] = 'You have creatad book successfully.'
		    redirect_to book_path(@book.id)
		 else
		 	@books = Book.all
		 	@user = current_user
		 	render action: :index
		 end
	end

	def show
		@book = Book.new
		@books = Book.find(params[:id])
		@user = @books.user
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		    flash[:notice_a] = 'You have updated book successfully.'
		    redirect_to book_path(@book.id)
		else
			@books = Book.find(params[:id])
			render action: :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end

	def correct_user
		book = Book.find(params[:id])
		if book.user.id != current_user.id
	      redirect_to books_path
	    end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @book = Book.new
  	@users = User.all
    @user_info = current_user
  end

  def show
    @books = Book.new
  	@user = User.find(params[:id])
    @book = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
        flash[:notice_a] = 'You have updated user successfully.'
        redirect_to user_path(@user.id)
     else
        @users = User.find(params[:id])
        render action: :edit
     end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    if params[:id].to_i != current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <div class="error_explanation">
            <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
              <ul>
               <% @book.errors.full_messages.each do |message| %>
               <li><%= message %></li>
               <% end %>
              </ul>
          </div>
        <% end %>
      <%= form_for(@book) do |f| %>
      <div class="field row">
       <label>Title</label>
       <%= f.text_field :title, class: "col-xs-12 field"  %>
      </div>
      <div class="field row">
       <label>Opinion</label>
       <%= f.text_area :body, class: "col-xs-12 field" %>
      </div>
      <div class="action row">
       <%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
      </div>
      <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <p><%= flash[:notice_a] %></p>
  <div class="row">
    <% if @book.errors.any? %>
      <div class="error_explanation">
      <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    <% end %>
  </div>
  <div class="row">
    <!-- ここから -->
  	<div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: 'jpg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>Introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
    <div class="row">
      <%= link_to "", edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>
    <h2>New book</h2>
      <%= form_for(@book) do |f| %>
      <div class="field row">
        <label class="book_title">Title</label>
          <%= f.text_field :title, class: "col-xs-12 book_title" %>
        </div>
      <div class="field row">
        <label class="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12 book_body"%>
      </div>
      <div class="action row">
          <%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
      </div>
      <% end %>
  	</div>
    <!-- ここまで -->
  	<div class="col-xs-9">
	  	<h2>Books</h2>
		　<table class="table table-hover table-inverse">
			 <thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
          <th colspan="3"></th>
        </tr>
			 </thead>
			 <tbody>
				<% @books.each do |book| %>
				<tr>
					<td><%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, format: 'jpg', fallback: "no_image.jpg", size: '50x50' %>
              <% end %>
            </td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			 </tbody>
		  </table>
	   </div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
  <p><%= flash[:notice_a] %></p>
  <div class="row">
    <!-- ここから -->
  	<div class="col-xs-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: 'jpg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
    <div class="row">
      <%= link_to "", edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>
    <h2>New book</h2>
      <%= form_for(@book) do |f| %>
      <div class="field row">
        <label class="book_title">Title</label>
          <%= f.text_field :title, class: "col-xs-12 book_title" %>
        </div>
      <div class="field row">
        <label class="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12 book_body" %>
      </div>
      <div class="action row">
          <%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
      </div>
      <% end %>
  	</div>
    <!-- ここまで -->
  	<div class="col-xs-9">
	  	<h2>Book detail</h2>
      <table class="table">
			 <tbody>
				<tr>
					<td>
            <%= link_to user_path(@books.user.id) do %>
            <%= attachment_image_tag @books.user, :profile_image, format: 'jpg', fallback: "no_image.jpg" ,size: '100x100'%>
            <br>
            <%= @books.user.name %>
            <% end %>
          </td>
					<td><%= link_to @books.title, book_path(@books.id) %></td>
					<td><%= @books.body %></td>
          <% if @books.user == current_user %>
          <td><%= link_to "Edit", edit_book_path(@books.id), class: "btn-sm btn-success" %></td>
          <td><%= link_to "Destroy", book_path(@books.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn-sm btn-danger" %></td>
          <% end %>
				</tr>
			 </tbody>
		  </table>
	</div>
	</div>
</div>

app/views/home/about.html.erb
<div class="container">
    <h1>Welcome to
        <span class="glyphicon glyphicon-book"></span>
         <strong>Bookers</strong>!
    </h1>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
   <div class="top-message col-md-offset-3 col-md-6">
	<h1>welcome to
	    <span class="glyphicon glyphicon-book"></span>
	    <strong>Bookers</strong>
	    !!
	</h1>
	<p>In
	   <span class="glyphicon glyphicon-book"></span>
	   <strong>Bookers</strong>
	</p>
	<p>you can share and exchange your opinions , inpressions , and emotions</p>
	<p>about various books!</p>
   <div class="btn-wrapper">
	<div class="row">
		<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
	</div>
	<div class="row">
		<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
	</div>
   </div>
   </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <header class=" navbar navbar_fixed_top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %></li>
            <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %></li>
            <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
          <% else %>
            <li><%= link_to " Home", "/", class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to " About", "/home/about", class: "glyphicon glyphicon-link about" %></li>
            <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign up" %></li>
            <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in login" %></li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <body>
      <div class="container">
        <p class="notice"><%= flash[:notice] %></p>
    <%= yield %>
      </div>
    </body>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">CopyRight Infratop.inc</div>
        </div>
      </div>
    </footer>
</html>

app/views/users/edit.html.erb
<div class="container">
  <h2>User info</h2>
  <%= form_for(@user) do |f| %>
   <% if @user.errors.any? %>
   <div class="error_explanation">
      <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
        <% end %>
      </ul>
   </div>
   <% end %>
   <div class="field">
    <label>Name</label>
    <%= f.text_field :name %>
   </div>
   <div class="field">
    <label>Image</label>
    <%= f.attachment_field :profile_image %>
   </div>
   <div class="field">
    <label>Introduction</label>
    <%= f.text_area :introduction %>
   </div>
   <div class="actions">
    <%= f.submit "Update User" %>
   </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <p><%= flash[:notice_a] %></p>
  <div class="row">
    <!-- ここから -->
  	<div class="col-xs-3">
     <h2>User info</h2>
     <%= attachment_image_tag @user_info, :profile_image, :fill, 100,100, format: 'jpg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user_info.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user_info.introduction %></th>
          </tr>
        </tbody>
      </table>
    <div class="row">
      <%= link_to "", edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>
    <h2>New book</h2>
      <%= form_for(@book) do |f| %>
      <div class="field row">
        <label class="book_title">Title</label>
          <%= f.text_field :title, class: "col-xs-12 book_title" %>
        </div>
      <div class="field row">
        <label class="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12 book_body"%>
      </div>
      <div class="action row">
          <%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
      </div>
      <% end %>
    </div>
    <!-- ここまで -->
  	<div class="col-xs-9">
	  	<h2>Users</h2>
		  <table class="table">
			 <thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			 </thead>
			 <tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag user, :profile_image, format: 'jpg', fallback: "no_image.jpg", size: '50x50' %></td>
					<td><%= user.name %></td>
					<td><%= link_to"Show", user_path(user.id) %></td>
				</tr>
				<% end %>
			 </tbody>
		  </table>
	  </div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <p><%= flash[:notice_a] %></p>
  <div class="row">
  	<!-- ここから -->
  	<div class="col-xs-3">
		<h2>User info</h2>
	    <%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: 'jpg', fallback: "no_image.jpg" %>
	      <table class="table">
	      	<tbody>
	        	<tr>
	          		<th>name</th>
	          		<th><%= @user.name %></th>
	        	</tr>
	        	<tr>
	          		<th>introduction</th>
	          		<th><%= @user.introduction %></th>
	        	</tr>
	        </tbody>
	      </table>
	<div class="row">
	  <%= link_to "", edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
	</div>
	<h2>New book</h2>
	  <%= form_for(@books) do |f| %>
	  <div class="field row">
        <label class="book_title">Title</label>
          <%= f.text_field :title, class: "col-xs-12 book_title" %>
      </div>
      <div class="field row">
        <label class="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "col-xs-12 book_body"%>
      </div>
      <div class="action row">
          <%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
      </div>
      <% end %>
  	</div>
    <!-- ここまで -->
  	<div class="col-xs-9">
	  	<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @book.each do |book| %>
				<tr>
					<td><%= attachment_image_tag @user, :profile_image, format: 'jpg', fallback: "no_image.jpg", size: '50x50' %></td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
  </div>
</div>